### ISSUE TITLE
Add IE9 compatibility header

### ISSUE THREAD

**Issue by rpokorny** [ozone-development/hud-ui#66]
In order to get IE9 to render in standards mode within the production environment, we should add an X-UA-Compatible meta tag to index.html.

Example:

<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>

**Comment by mparizernc** [comment]
I set IE9 to be set to Compatibility Mode by default. I then verified that Center and HUD did not appear before this fix. I then deployed with the fix and both appeared correctly.
