### ISSUE TITLE
HTML Title tag needs to be configurable 

### ISSUE THREAD

**Issue by tonyalletag** [ozone-development/hud-ui#67]
Production users are seeing incorrect title in there tabs, This also is showing up in metrics as OZONE HUD instead of AppsMall HUD

title - Needs to be configurable - title

**Comment by sdeighan** [comment]
Discussion ongoing in center-ui #91

**Comment by mparizernc** [comment]
All Browsers
Verified that the the tab name changes for both the HUD and Center based on the configuration.
